version: "1.0.0"

business:
  id: "bella-salon"
  name: "Bella Hair Salon"
  description: "Premium hair styling, coloring, and treatments in the heart of Florence. Expert stylists, luxury products, and personalized service."
  timezone: "Europe/Rome"
  locale: "it-IT"
  currency: "EUR"

contact:
  address:
    street: "Via della Spada 12"
    city: "Firenze"
    state: "Toscana"
    postalCode: "50123"
    country: "IT"
  email: "info@bellasalon.it"
  phone: "+390552456789"
  website: "https://bellasalon.it"

branding:
  primaryColor: "#ec4899"
  secondaryColor: "#f97316"
  logoUrl: "https://example.com/salon-logo.png"
  coverImageUrl: "https://example.com/salon-cover.jpg"
  faviconUrl: "https://example.com/salon-favicon.ico"

timeSlotDuration: 30

availability:
  - day: monday
    open: "10:00"
    close: "19:00"
    enabled: true
  - day: tuesday
    open: "09:00"
    close: "20:00"
    enabled: true
  - day: wednesday
    open: "09:00"
    close: "20:00"
    enabled: true
  - day: thursday
    open: "09:00"
    close: "20:00"
    enabled: true
  - day: friday
    open: "09:00"
    close: "21:00"
    enabled: true
  - day: saturday
    open: "08:00"
    close: "18:00"
    enabled: true
  - day: sunday
    open: "09:00"
    close: "17:00"
    enabled: false

availabilityExceptions:
  - date: "2025-12-25"
    reason: "Christmas Day"
    closed: true
  - date: "2026-01-01"
    reason: "New Year's Day"
    closed: true
  - date: "2026-08-15"
    reason: "Ferragosto"
    closed: true

categories:
  - id: "haircuts"
    name: "Tagli di Capelli"
    description: "Professional haircuts and styling"
    sortOrder: 0
    services:
      - id: "womens-cut"
        name: "Taglio Donna"
        description: "Haircut for women, includes wash and blow dry"
        duration: 60
        price: 4500
        color: "#8b5cf6"
        sortOrder: 0
        enabled: true
        requiresDeposit: false
        bufferBefore: 5
        bufferAfter: 10

      - id: "mens-cut"
        name: "Taglio Uomo"
        description: "Men's haircut with styling"
        duration: 30
        price: 3000
        color: "#6366f1"
        sortOrder: 1
        enabled: true
        requiresDeposit: false
        bufferBefore: 5
        bufferAfter: 10

      - id: "kids-cut"
        name: "Taglio Bambini"
        description: "Haircut for children under 12"
        duration: 30
        price: 2500
        color: "#ec4899"
        sortOrder: 2
        enabled: true
        requiresDeposit: false
        bufferBefore: 5
        bufferAfter: 10

  - id: "coloring"
    name: "Colorazione"
    description: "Hair coloring and highlights"
    sortOrder: 1
    services:
      - id: "full-color"
        name: "Colore Completo"
        description: "Full hair coloring service with premium products"
        duration: 120
        price: 8500
        color: "#f59e0b"
        sortOrder: 0
        enabled: true
        requiresDeposit: true
        depositAmount: 2500
        bufferBefore: 10
        bufferAfter: 15

      - id: "highlights"
        name: "Colpi di Sole"
        description: "Professional highlights for dimension and brightness"
        duration: 150
        price: 9500
        color: "#fbbf24"
        sortOrder: 1
        enabled: true
        requiresDeposit: true
        depositAmount: 3000
        bufferBefore: 10
        bufferAfter: 15

      - id: "balayage"
        name: "Balayage"
        description: "Hand-painted highlights for natural sun-kissed look"
        duration: 180
        price: 12000
        color: "#f97316"
        sortOrder: 2
        enabled: true
        requiresDeposit: true
        depositAmount: 4000
        bufferBefore: 10
        bufferAfter: 20

  - id: "treatments"
    name: "Trattamenti"
    description: "Hair treatments and care"
    sortOrder: 2
    services:
      - id: "keratin-treatment"
        name: "Trattamento alla Cheratina"
        description: "Smoothing keratin treatment for frizz-free hair"
        duration: 180
        price: 15000
        color: "#14b8a6"
        sortOrder: 0
        enabled: true
        requiresDeposit: true
        depositAmount: 5000
        bufferBefore: 15
        bufferAfter: 20

      - id: "deep-conditioning"
        name: "Maschera Nutriente Profonda"
        description: "Intensive conditioning treatment for damaged hair"
        duration: 60
        price: 3500
        color: "#06b6d4"
        sortOrder: 1
        enabled: true
        requiresDeposit: false
        bufferBefore: 5
        bufferAfter: 10

  - id: "styling"
    name: "Piega e Styling"
    description: "Blow dry and special occasion styling"
    sortOrder: 3
    services:
      - id: "blowout"
        name: "Piega"
        description: "Professional blow dry and styling"
        duration: 60
        price: 3500
        color: "#a855f7"
        sortOrder: 0
        enabled: true
        requiresDeposit: false
        bufferBefore: 5
        bufferAfter: 10

      - id: "updo"
        name: "Acconciatura"
        description: "Elegant updo for special occasions"
        duration: 90
        price: 7500
        color: "#c026d3"
        sortOrder: 1
        enabled: true
        requiresDeposit: true
        depositAmount: 2000
        bufferBefore: 10
        bufferAfter: 15

bookingRequirements:
  requireEmail: true
  requirePhone: true
  requireName: true
  allowGuestBooking: true
  requireEmailVerification: false
  requirePhoneVerification: false
  customFields:
    - id: "hair-length"
      label: "Lunghezza attuale dei capelli"
      type: "select"
      required: false
      options:
        - "Corto (sopra le spalle)"
        - "Medio (alle spalle)"
        - "Lungo (sotto le spalle)"
    - id: "special-requests"
      label: "Richieste speciali o ispirazioni"
      type: "textarea"
      required: false
      placeholder: "Descrivi lo stile desiderato o condividi foto di ispirazione"
      maxLength: 300

bookingLimits:
  maxSimultaneousBookings: 4
  advanceBookingDays: 60
  minAdvanceBookingMinutes: 120
  maxBookingsPerCustomerPerDay: 1

cancellationPolicy:
  allowCancellation: true
  cancellationDeadlineHours: 24
  allowRescheduling: true
  rescheduleDeadlineHours: 12
  refundPolicy: "partial"
  partialRefundPercentage: 50

notifications:
  sendConfirmationEmail: true
  sendReminderEmail: true
  reminderHoursBefore: 24
  sendConfirmationSMS: false
  sendReminderSMS: false
  ownerNotificationEmail: "manager@bellasalon.it"
  notifyOwnerOnNewBooking: true
  notifyOwnerOnCancellation: true

features:
  enableOnlinePayments: true
  enableWaitlist: true
  enableReviews: true
  enableMultipleStaff: true

metadata:
  parkingAvailable: true
  wheelchairAccessible: true
  languages: ["it", "en"]
  acceptsWalkIns: true
  dresscode: "Casual"
