version: "1.0.0"

business:
  id: "terme-firenze"
  name: "Terme di Firenze"
  description: "Complesso termale a Firenze che offre trattamenti benessere, bagni termali, saune e aree relax. Un'oasi di pace nel cuore della città."
  timezone: "Europe/Rome"
  locale: "it-IT"
  currency: "EUR"

contact:
  address:
    street: "Viale Michelangelo, 1"
    city: "Firenze"
    state: "Toscana"
    postalCode: "50125"
    country: "IT"
  email: "info@termedifirenze.it"
  phone: "+39055398127"
  website: "https://www.termedifirenze.it"
  latitude: 43.759
  longitude: 11.265

branding:
  primaryColor: "#2563eb"
  secondaryColor: "#60a5fa"
  logoUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=400&fit=crop"
  coverImageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=600&fit=crop"
  profileImageUrl: "https://images.unsplash.com/photo-1596178060810-fb4bd482ee2c?w=400&h=400&fit=crop"
  faviconUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=64&h=64&fit=crop"

timeSlotDuration: 60

availability:
  - day: monday
    open: "10:00"
    close: "22:00"
    enabled: true
  - day: tuesday
    open: "10:00"
    close: "22:00"
    enabled: true
  - day: wednesday
    open: "10:00"
    close: "22:00"
    enabled: true
  - day: thursday
    open: "10:00"
    close: "22:00"
    enabled: true
  - day: friday
    open: "10:00"
    close: "23:00"
    enabled: true
  - day: saturday
    open: "09:00"
    close: "23:00"
    enabled: true
  - day: sunday
    open: "09:00"
    close: "21:00"
    enabled: true

availabilityExceptions:
  - date: "2025-12-25"
    reason: "Natale"
    closed: true
  - date: "2025-12-26"
    reason: "Santo Stefano"
    closed: true
  - date: "2026-01-01"
    reason: "Capodanno"
    closed: true
  - date: "2026-01-06"
    reason: "Epifania"
    closed: true
  - date: "2026-08-15"
    reason: "Ferragosto"
    closed: true

categories:
  - id: "massaggi"
    name: "Massaggi"
    description: "Massaggi rilassanti e terapeutici per il benessere del corpo"
    sortOrder: 0
    services:
      - id: "massaggio-svedese"
        name: "Massaggio Svedese"
        description: "Massaggio classico svedese per rilassamento muscolare"
        duration: 60
        price: 8000
        color: "#059669"
        sortOrder: 0
        enabled: true
        requiresDeposit: false
        bufferBefore: 15
        bufferAfter: 15

      - id: "massaggio-profondo"
        name: "Massaggio Tissutale Profondo"
        description: "Massaggio terapeutico per tensioni muscolari profonde"
        duration: 75
        price: 9500
        color: "#047857"
        sortOrder: 1
        enabled: true
        requiresDeposit: false
        bufferBefore: 15
        bufferAfter: 15

      - id: "massaggio-aromaterapia"
        name: "Massaggio con Aromaterapia"
        description: "Massaggio rilassante con oli essenziali naturali"
        duration: 90
        price: 11000
        color: "#065f46"
        sortOrder: 2
        enabled: true
        requiresDeposit: true
        depositAmount: 3000
        bufferBefore: 20
        bufferAfter: 20

  - id: "trattamenti-viso"
    name: "Trattamenti Viso"
    description: "Trattamenti estetici per il viso e la pelle"
    sortOrder: 1
    services:
      - id: "pulizia-viso"
        name: "Pulizia del Viso"
        description: "Pulizia profonda del viso con estrazione punti neri"
        duration: 60
        price: 7000
        color: "#7c3aed"
        sortOrder: 0
        enabled: true
        requiresDeposit: false
        bufferBefore: 10
        bufferAfter: 10

      - id: "maschera-idratante"
        name: "Maschera Idratante"
        description: "Trattamento idratante con maschera viso personalizzata"
        duration: 45
        price: 5500
        color: "#6d28d9"
        sortOrder: 1
        enabled: true
        requiresDeposit: false
        bufferBefore: 10
        bufferAfter: 10

      - id: "trattamento-antiage"
        name: "Trattamento Anti-Age"
        description: "Trattamento antirughe con prodotti premium"
        duration: 90
        price: 12000
        color: "#5b21b6"
        sortOrder: 2
        enabled: true
        requiresDeposit: true
        depositAmount: 4000
        bufferBefore: 15
        bufferAfter: 15

  - id: "bagni-termali"
    name: "Bagni Termali"
    description: "Esperienze termali con piscine e saune"
    sortOrder: 2
    services:
      - id: "ingresso-termale"
        name: "Ingresso Alle Terme"
        description: "Accesso completo alle aree termali con piscine e saune"
        duration: 180
        price: 25000
        color: "#dc2626"
        sortOrder: 0
        enabled: true
        requiresDeposit: true
        depositAmount: 5000
        bufferBefore: 30
        bufferAfter: 30

      - id: "pacchetto-wellness"
        name: "Pacchetto Wellness Completo"
        description: "Massaggio, trattamento viso e accesso alle terme"
        duration: 240
        price: 35000
        color: "#b91c1c"
        sortOrder: 1
        enabled: true
        requiresDeposit: true
        depositAmount: 10000
        bufferBefore: 45
        bufferAfter: 45

bookingRequirements:
  requireEmail: true
  requirePhone: true
  requireName: true
  allowGuestBooking: true
  requireEmailVerification: false
  requirePhoneVerification: false
  customFields:
    - id: "therapist-preference"
      label: "Preferenza Terapeuta"
      type: "select"
      required: false
      options:
        - "Qualsiasi terapeuta"
        - "Terapeuta donna"
        - "Terapeuta uomo"
    - id: "skin-type"
      label: "Tipo di Pelle"
      type: "select"
      required: false
      options:
        - "Normale"
        - "Secca"
        - "Grassa"
        - "Sensibile"
        - "Mista"
    - id: "special-requests"
      label: "Richieste Speciali"
      type: "textarea"
      required: false
      placeholder: "Allergie, preferenze o richieste particolari"
      maxLength: 300

bookingLimits:
  maxSimultaneousBookings: 2
  advanceBookingDays: 90
  minAdvanceBookingMinutes: 240
  maxBookingsPerCustomerPerDay: 1

cancellationPolicy:
  allowCancellation: true
  cancellationDeadlineHours: 24
  allowRescheduling: true
  rescheduleDeadlineHours: 12
  refundPolicy: "partial"
  partialRefundPercentage: 70

notifications:
  sendConfirmationEmail: true
  sendReminderEmail: true
  reminderHoursBefore: 24
  sendConfirmationSMS: true
  sendReminderSMS: true
  ownerNotificationEmail: "reservations@termedifirenze.it"
  notifyOwnerOnNewBooking: true
  notifyOwnerOnCancellation: true

features:
  enableOnlinePayments: true
  enableWaitlist: true
  enableReviews: true
  enableMultipleStaff: true

metadata:
  parkingAvailable: true
  wheelchairAccessible: true
  languages: ["it", "en", "fr", "de"]
  acceptsWalkIns: false
  dresscode: "Abbigliamento da spa - Accappatoi forniti"