[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Disable caching for all API routes to ensure fresh data
[[headers]]
  for = "/api/appointments"
  [headers.values]
    Cache-Control = "no-store"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/api/owner/*"
  [headers.values]
    Cache-Control = "no-store"
    Pragma = "no-cache"
    Expires = "0"
