[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Disable caching for all API routes to ensure fresh data
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "private, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
