[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Redirect all routes to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
